dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}  
autofetch_sources: True
networks:
  default: development
  development:
    verify: False
  rinkeby:
    verify: True
  ganache:
    verify: False

